debug = true
# TM_CCOEFF 图像匹配的阈值 (0.0 ~ 1.0)
image_threshold = 0.9
# 游戏界面操作检测画面的间隔时间 (秒)
frame_delay = 0.5

[device]
# 可以指定一个特定的 ADB 设备
adb_serial = ''
# 屏幕像素尺寸 (宽, 高)
screen_size = [2160, 1080]
# 下落条的左下、左上、右上、右下四个顶点的坐标
corner_ld = [134, 1080]
corner_lt = [1036, 0]
corner_rt = [1126, 0]
corner_rd = [2024, 1080]
# 用来识别谱面开始的竖向线的 Y 坐标
visual_y = 200
# 模拟触摸的 Y 坐标
touch_y = 1000
# 视频串流的码率
bitrate = 8_000_000
# 视频串流的帧率
fps = 60